---
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
