---
formatter: "markdown table"

version: ">= 0.19.0"

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Examples

  An simple example of the default configuration can be found below:

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  A more complex example can be found below:

  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
