- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "dependencies"
  color: "fbca04"
  description: "Update of dependencies"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "008672"
  description: "New feature or request"
- name: "github_actions"
  color: "000000"
  description: "Pull requests that update GitHub Actions code"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "ignore-for-release"
  color: ededed"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "python"
  color: "2b67c6"
  description: "Pull requests that update Python code"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "size/XS"
  color: "0e8a16"
  description: "PR with minimal changes"
- name: "size/S"
  color: "0EFABD"
  description: "PR with small changes"
- name: "size/M"
  color: "75CEF4"
  description: "PR with medium changes"
- name: "size/L"
  color: "FBCA04"
  description: "PR with large changes"
- name: "size/XL"
  color: "B60205"
  description: "PR with very large changes"
- name: "stale"
  color: "b60205"
  description: "Marks an issue or pull request as stale"
- name: "terraform"
  color: "5319E7"
  description: "Related to Terraform"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
