---
name: conventional-release-labels

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  label:
    name: conventional-release-labels

    runs-on: ubuntu-22.04

    steps:
      - uses: bcoe/conventional-release-labels@v1.3.1
