---
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: release-please

    runs-on: ubuntu-24.04

    steps:
      - uses: googleapis/release-please-action@v4.1.4
        with:
          token: ${{ secrets.PAT }}
