---
name: tfsec

on:
  pull_request:
    paths:
      - "**.tf"

jobs:
  tfsec:
    name: tfsec PR commenter

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: Run tfsec PR commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
